/** Interface autonome servie par FlightOps sur le réseau local. Aucun framework ni CDN : elle
 * reste disponible même sans Internet et ne dépend que du PC qui fait tourner FlightOps. */
export const TABLET_PAGE_HTML = String.raw`<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#0a1020">
  <title>FlightOps · Tablette</title>
  <style>
    :root{color-scheme:dark;--bg:#070b14;--panel:#101725;--soft:#182235;--line:#26344a;--text:#f7f9fc;--muted:#8fa1bc;--blue:#4d8bff;--green:#27d69b;--orange:#ffad42;--red:#ff6678}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% -20%,#17284a 0,var(--bg) 43%);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;min-height:100vh}button,input,select{font:inherit}button{cursor:pointer}.hidden{display:none!important}
    .login{min-height:100vh;display:grid;place-items:center;padding:24px}.login-card{width:min(430px,100%);padding:28px;border:1px solid var(--line);border-radius:24px;background:rgba(16,23,37,.94);box-shadow:0 24px 70px #0008}.brand{display:flex;align-items:center;gap:12px;font-size:24px;font-weight:850}.brand-mark{display:grid;place-items:center;width:44px;height:44px;border-radius:14px;background:linear-gradient(135deg,#377cff,#65a3ff);font-size:22px}.login p{color:var(--muted);line-height:1.55}.pin-row{display:grid;grid-template-columns:1fr auto;gap:10px}.pin-row input{min-width:0;padding:14px;border:1px solid var(--line);border-radius:12px;background:#090f1c;color:var(--text);font-size:21px;font-weight:800;letter-spacing:.18em;text-align:center}.primary{border:0;border-radius:12px;background:var(--blue);color:white;font-weight:800;padding:12px 18px}.error{color:var(--red);font-size:13px}
    .app{width:min(1420px,100%);margin:auto;padding:max(14px,env(safe-area-inset-top)) 16px max(24px,env(safe-area-inset-bottom))}.topbar{position:sticky;top:0;z-index:10;display:flex;align-items:center;justify-content:space-between;gap:14px;padding:12px 2px;background:linear-gradient(var(--bg) 72%,transparent)}.topbar .brand{font-size:18px}.status{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px;font-weight:700}.dot{width:9px;height:9px;border-radius:50%;background:var(--red);box-shadow:0 0 0 4px #ff66781d}.dot.ok{background:var(--green);box-shadow:0 0 0 4px #27d69b20}
    .layout{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(320px,.7fr);gap:14px}.stack{display:flex;flex-direction:column;gap:14px}.card{min-width:0;padding:17px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,rgba(18,27,44,.98),rgba(13,19,31,.98));box-shadow:0 8px 28px #0003}.card h2{margin:0 0 13px;color:#b9c8dd;font-size:12px;text-transform:uppercase;letter-spacing:.1em}.hero{padding:20px}.hero-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.airline{color:#9ab9f8;font-size:13px;font-weight:800}.flight-number{font-size:25px;font-weight:900}.route{display:grid;grid-template-columns:1fr minmax(110px,.55fr) 1fr;align-items:center;margin-top:20px}.airport:last-child{text-align:right}.icao{font-size:34px;font-weight:900;letter-spacing:.04em}.airport small{color:var(--muted)}.route-line{display:flex;align-items:center;gap:8px;color:var(--blue)}.route-line:before,.route-line:after{content:"";height:1px;background:currentColor;flex:1}.badge{padding:7px 10px;border-radius:999px;background:#4d8bff1f;color:#8eb6ff;font-size:11px;font-weight:850;text-transform:uppercase}.empty{color:var(--muted);line-height:1.5}
    .metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.metric{padding:13px;border-radius:14px;background:var(--soft);border:1px solid #ffffff08}.metric span{display:block;color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.07em}.metric strong{display:block;margin-top:5px;font-size:20px;font-variant-numeric:tabular-nums}
    .map{height:235px;border-radius:13px;background:radial-gradient(circle at center,#172b47,#080e19);overflow:hidden}.map svg{width:100%;height:100%}.map-empty{height:100%;display:grid;place-items:center;color:var(--muted);font-size:13px}.flight-controls{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px}.flight-controls select,.metar-row input{min-width:0;padding:11px;border:1px solid var(--line);border-radius:11px;background:#090f1c;color:var(--text)}.danger{border:1px solid #ff667855;border-radius:11px;background:#ff667814;color:#ff8b98;font-weight:800;padding:10px 13px}.secondary{border:1px solid var(--line);border-radius:11px;background:var(--soft);color:var(--text);font-weight:750;padding:10px 13px}
    .metar-row{display:grid;grid-template-columns:1fr auto;gap:8px}.metar-shortcuts{display:flex;flex-wrap:wrap;gap:7px;margin-bottom:9px}.metar-shortcuts button{border:1px solid var(--line);border-radius:999px;background:var(--soft);color:#bed0e9;padding:6px 10px;font-size:11px}.metar-box{margin-top:10px;padding:12px;border-radius:12px;background:#090f1c}.metar-box code{display:block;color:#d8e4f6;white-space:pre-wrap;word-break:break-word;font-size:11px}.weather-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:9px}.weather-grid span{padding:8px;border-radius:9px;background:var(--soft);color:var(--muted);font-size:10px}.weather-grid strong{display:block;color:var(--text);font-size:12px;margin-top:2px}
    .announcement-current{display:flex;align-items:center;justify-content:space-between;gap:9px;margin-bottom:11px;padding:10px;border:1px solid #27d69b50;border-radius:12px;background:#27d69b0d}.announcement-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.announcement{min-width:0;text-align:left;border:1px solid var(--line);border-radius:11px;background:var(--soft);color:var(--text);padding:9px}.announcement:disabled{opacity:.38;cursor:not-allowed}.announcement.active{border-color:var(--green);color:var(--green)}.announcement b{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:11px}.announcement small{color:var(--muted);font-size:9px}
    .events{max-height:330px;overflow:auto}.event{display:grid;grid-template-columns:58px 1fr;gap:8px;padding:9px 0;border-bottom:1px solid var(--line);font-size:11px}.event:last-child{border:0}.event time{color:#7ca8ff;font-variant-numeric:tabular-nums}.event span{color:#c1cde0}
    @media(max-width:900px){.layout{grid-template-columns:1fr}.topbar{backdrop-filter:blur(12px)}.map{height:210px}}@media(max-width:560px){.app{padding-left:10px;padding-right:10px}.route{grid-template-columns:1fr 70px 1fr}.icao{font-size:27px}.metrics{grid-template-columns:repeat(2,1fr)}.announcement-grid{grid-template-columns:1fr}.flight-controls{grid-template-columns:1fr}.hero-head{flex-direction:column}.card{padding:14px}}
  </style>
</head>
<body>
  <section id="login" class="login"><div class="login-card"><div class="brand"><span class="brand-mark">✈</span> FlightOps Tablette</div><p>Entrez le code d’appairage affiché dans les paramètres de FlightOps sur le PC.</p><form id="login-form" class="pin-row"><input id="pin" inputmode="numeric" maxlength="6" autocomplete="one-time-code" placeholder="000000"><button class="primary">Connecter</button></form><p id="login-error" class="error hidden"></p><p><small>La tablette et le PC doivent être connectés au même réseau Wi‑Fi.</small></p></div></section>
  <main id="app" class="app hidden"><header class="topbar"><div class="brand"><span class="brand-mark">✈</span> FlightOps</div><div class="status"><span id="status-dot" class="dot"></span><span id="status-text">Connexion…</span></div></header><div class="layout"><div class="stack">
    <section id="flight-card" class="card hero"><div class="empty">Aucun vol suivi.</div></section>
    <section class="card"><h2>Informations en direct</h2><div id="metrics" class="metrics"></div></section>
    <section class="card"><h2>Trajectoire parcourue</h2><div id="map" class="map"><div class="map-empty">La trajectoire apparaîtra pendant le vol.</div></div></section>
    <section class="card"><h2>Choisir le vol suivi</h2><div class="flight-controls"><select id="flight-select"></select><button id="arm-button" class="primary">Démarrer / reprendre</button></div><button id="disarm-button" class="danger" style="margin-top:9px;width:100%">Arrêter le suivi</button></section>
  </div><aside class="stack">
    <section class="card"><h2>Météo</h2><div id="metar-shortcuts" class="metar-shortcuts"></div><form id="metar-form" class="metar-row"><input id="metar-icao" maxlength="4" placeholder="OACI (LFPG)"><button class="secondary">METAR</button></form><div id="metar-result"></div></section>
    <section class="card"><h2>Annonces cabine</h2><div id="cabin-status" class="empty">Aucun vol actif.</div><div id="announcements" class="announcement-grid"></div></section>
    <section class="card"><h2>Journal de vol</h2><div id="events" class="events"><div class="empty">Aucun évènement.</div></div></section>
  </aside></div></main>
<script>
(function(){
  var pin=sessionStorage.getItem('flightops-pin')||'';var source=null;var snapshot=null;
  var defs=[
    ["boarding_music","♫","Musique d’embarquement"],["boarding_welcome","👋","Boarding Welcome"],["boarding_complete","✓","Boarding Complete"],["arm_doors","🔒","Arm Doors"],["presafety_briefing","🎙","Presafety Briefing"],["safety_briefing","🦺","Safety Briefing"],["cabin_dim_takeoff","☾","Cabin Dim Takeoff"],["crew_seat_takeoff","💺","Crew Seat Takeoff"],["after_takeoff_9000","↗","Après décollage · 9 000 ft"],["descent_seatbelt","↘","Descent Seat Belt"],["crew_seat_landing","💺","Crew Seat Landing"],["after_landing","🛬","Après atterrissage"],["disarm_doors","🔓","Disarm Doors"],["disembark_started","🚪","Disembark Started"]
  ];
  function e(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function num(v,d){return Number.isFinite(v)?Math.round(v).toLocaleString('fr-FR')+' '+d:'—'}
  function utc(s){if(!s)return '—';try{return new Intl.DateTimeFormat('fr-FR',{hour:'2-digit',minute:'2-digit',timeZone:'UTC'}).format(new Date(s))+' UTC'}catch(_){return '—'}}
  function post(path,body){return fetch(path+(path.indexOf('?')>=0?'&':'?')+'pin='+encodeURIComponent(pin),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body||{})}).then(function(r){if(!r.ok)throw new Error('Commande refusée');return r.json()})}
  function connect(){if(source)source.close();source=new EventSource('/api/stream?pin='+encodeURIComponent(pin));source.onmessage=function(x){snapshot=JSON.parse(x.data);render()};source.onerror=function(){document.getElementById('status-dot').className='dot';document.getElementById('status-text').textContent='PC inaccessible'}}
  function login(){fetch('/api/snapshot?pin='+encodeURIComponent(pin)).then(function(r){if(!r.ok)throw new Error('Code incorrect');return r.json()}).then(function(s){sessionStorage.setItem('flightops-pin',pin);snapshot=s;document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');render();connect()}).catch(function(err){var el=document.getElementById('login-error');el.textContent=err.message;el.classList.remove('hidden')})}
  function render(){if(!snapshot)return;var t=snapshot.telemetry,f=snapshot.flight,connected=snapshot.simconnectStatus==='connected';document.getElementById('status-dot').className='dot'+(connected?' ok':'');document.getElementById('status-text').textContent=connected?'SimConnect connecté':'SimConnect '+snapshot.simconnectStatus;
    document.getElementById('flight-card').innerHTML=f?'<div class="hero-head"><div><div class="airline">'+e(f.company.displayName)+' · '+e(f.aircraft?f.aircraft.type:'Avion non renseigné')+'</div><div class="flight-number">'+e(f.flightNumber)+' <small>'+e(f.callsignDisplay)+'</small></div></div><span class="badge">'+e(f.status==='in_progress'?'En cours':'Prêt')+'</span></div><div class="route"><div class="airport"><div class="icao">'+e(f.departureIcao)+'</div><small>'+utc(f.scheduledDeparture)+'</small></div><div class="route-line">✈</div><div class="airport"><div class="icao">'+e(f.arrivalIcao)+'</div><small>'+utc(f.scheduledArrival)+'</small></div></div>':'<div class="empty">Aucun vol suivi. Sélectionnez un vol ci-dessous pour démarrer ou reprendre le suivi.</div>';
    var metrics=[['Altitude',t?num(t.altitude,'ft'):'—'],['Cap',t?num(t.headingTrue,'°'):'—'],['Vitesse sol',t?num(t.groundVelocity,'kt'):'—'],['Vitesse verticale',t?num(t.verticalSpeed,'fpm'):'—'],['Carburant',t?num(t.fuelTotalWeight,'kg'):'—'],['État',t?(t.onGround?'Au sol':'En vol'):'—']];document.getElementById('metrics').innerHTML=metrics.map(function(x){return '<div class="metric"><span>'+x[0]+'</span><strong>'+x[1]+'</strong></div>'}).join('');
    var select=document.getElementById('flight-select'),old=select.value;select.innerHTML='<option value="">Sélectionner un vol…</option>'+snapshot.availableFlights.map(function(x){return '<option value="'+x.id+'">'+e(x.flightNumber+' · '+x.departureIcao+' → '+x.arrivalIcao)+'</option>'}).join('');if(old)select.value=old;else if(snapshot.armedFlightId)select.value=String(snapshot.armedFlightId);document.getElementById('disarm-button').disabled=!snapshot.armedFlightId;
    renderMap(snapshot.path,t);renderMetarShortcuts(f);renderCabin(snapshot.cabin);renderEvents(snapshot.events)
  }
  function renderMap(path,t){var pts=(path||[]).slice(-1000);if(t&&Number.isFinite(t.latitude)&&Number.isFinite(t.longitude))pts.push({lat:t.latitude,lon:t.longitude});if(pts.length<2){document.getElementById('map').innerHTML='<div class="map-empty">La trajectoire apparaîtra pendant le vol.</div>';return}var lats=pts.map(function(p){return p.lat}),lons=pts.map(function(p){return p.lon}),minA=Math.min.apply(null,lats),maxA=Math.max.apply(null,lats),minO=Math.min.apply(null,lons),maxO=Math.max.apply(null,lons),da=Math.max(maxA-minA,.01),doo=Math.max(maxO-minO,.01);function xy(p){return [20+(p.lon-minO)/doo*760,220-(p.lat-minA)/da*200]}var poly=pts.map(function(p){return xy(p).join(',')}).join(' '),last=xy(pts[pts.length-1]);document.getElementById('map').innerHTML='<svg viewBox="0 0 800 240" preserveAspectRatio="none"><defs><pattern id="g" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="#35506e" stroke-opacity=".22"/></pattern></defs><rect width="800" height="240" fill="url(#g)"/><polyline points="'+poly+'" fill="none" stroke="#4d8bff" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><circle cx="'+last[0]+'" cy="'+last[1]+'" r="8" fill="#fff" stroke="#4d8bff" stroke-width="4"/></svg>'}
  function renderMetarShortcuts(f){var arr=f?[f.departureIcao,f.arrivalIcao,f.alternateIcao].filter(Boolean):[];document.getElementById('metar-shortcuts').innerHTML=arr.map(function(x){return '<button type="button" data-icao="'+e(x)+'">'+e(x)+'</button>'}).join('');document.querySelectorAll('[data-icao]').forEach(function(b){b.onclick=function(){loadMetar(b.dataset.icao)}})}
  function loadMetar(code){code=String(code||'').trim().toUpperCase();if(!/^[A-Z0-9]{4}$/.test(code))return;var out=document.getElementById('metar-result');out.innerHTML='<div class="metar-box">Chargement…</div>';fetch('/api/metar?pin='+encodeURIComponent(pin)+'&icao='+encodeURIComponent(code)).then(function(r){return r.json().then(function(j){if(!r.ok)throw new Error(j.error||'METAR indisponible');return j})}).then(function(j){var raw=j.metar,wind=(raw.match(/\b(\d{3}|VRB)(\d{2,3})(G\d{2,3})?KT\b/)||[]),temp=(raw.match(/\b(M?\d{2})\/(M?\d{2})\b/)||[]),qnh=(raw.match(/\bQ(\d{4})\b/)||[]);out.innerHTML='<div class="metar-box"><div class="weather-grid"><span>💨 Vent<strong>'+(wind[1]?e(wind[1]+'° · '+wind[2]+' kt'):'—')+'</strong></span><span>🌡 Température<strong>'+(temp[1]?e(temp[1].replace('M','-')+' °C'):'—')+'</strong></span><span>◉ QNH<strong>'+(qnh[1]?e(qnh[1]+' hPa'):'—')+'</strong></span></div><code>'+e(raw)+'</code></div>'}).catch(function(err){out.innerHTML='<p class="error">'+e(err.message)+'</p>'})}
  function renderCabin(c){var current=c.activeVoice||c.activeMusic,ready=c.automationReady,available=c.availableTypes||[],queued=c.queuedTypes||[];document.getElementById('cabin-status').innerHTML=current?'<div class="announcement-current"><div><small>Lecture en cours</small><br><b>'+e(label(current.type))+'</b></div><button id="stop-all" class="danger">Arrêter</button></div>':'<div class="empty" style="margin-bottom:10px">'+(c.company?e(c.company.displayName)+(ready?' · prête':' · automatisation en attente'):'Aucune compagnie détectée')+'</div>';var stop=document.getElementById('stop-all');if(stop)stop.onclick=function(){post('/api/cabin',{action:'stop_all'})};document.getElementById('announcements').innerHTML=defs.map(function(d){var active=(current&&current.type===d[0])||queued.indexOf(d[0])>=0,ok=available.indexOf(d[0])>=0;return '<button class="announcement'+(active?' active':'')+'" data-type="'+d[0]+'" '+(!ok?'disabled':'')+'><b>'+d[1]+' '+e(d[2])+'</b><small>'+(active?'Arrêter':ok?'Lire':'Non configurée')+'</small></button>'}).join('');document.querySelectorAll('[data-type]').forEach(function(b){b.onclick=function(){var type=b.dataset.type,isActive=(current&&current.type===type)||queued.indexOf(type)>=0;post('/api/cabin',{action:isActive?'stop':'play',type:type})}})}
  function label(type){var d=defs.find(function(x){return x[0]===type});return d?d[2]:type}
  function renderEvents(events){var visible=(events||[]).filter(function(x){return x.type!=='operational_alert'}).slice(-40).reverse();document.getElementById('events').innerHTML=visible.length?visible.map(function(x){return '<div class="event"><time>'+utc(x.simTimeIso).replace(' UTC','')+'</time><span>'+e(x.message)+'</span></div>'}).join(''):'<div class="empty">Aucun évènement.</div>'}
  document.getElementById('login-form').onsubmit=function(ev){ev.preventDefault();pin=document.getElementById('pin').value.trim();login()};document.getElementById('arm-button').onclick=function(){var id=Number(document.getElementById('flight-select').value);if(id)post('/api/tracking/arm',{flightId:id})};document.getElementById('disarm-button').onclick=function(){post('/api/tracking/disarm',{})};document.getElementById('metar-form').onsubmit=function(ev){ev.preventDefault();loadMetar(document.getElementById('metar-icao').value)};if(pin)login();
})();
</script></body></html>`
